// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfwvisutdbfoanhqpafx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhmd3Zpc3V0ZGJmb2FuaHFwYWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Mjc4MjgsImV4cCI6MjA2NDQwMzgyOH0.LM6xFKV3qoNPcVRq3fx8KTV9gYRc9QGXGPCmxs54w4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);